name: Release
run-name: Release ${{ github.ref_name }}
permissions: write-all

on:
  push:
    tags:
      - "**@?v[0-9]+.[0-9]+.[0-9]+"

  workflow_dispatch:

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}

jobs:
  release-app:
    name: Release app
    uses: agusmgarcia/react-essentials/.github/workflows/release-app.yml@v0.14
    secrets:
      github-auth-token: ${{ secrets.GITHUB_TOKEN }}
